### ISSUE TITLE
Unable to configure CloundEventify with latest MassTransit using SQS - IsSupportedMessageType does not have an implementation

### ISSUE THREAD

**Issue by cjabbour** [riezebosch/MassTransit.CloudEvents#22]
Hi, in my `net7.0` basic console app, I'm using `MassTransit 8.2.3` and `MassTransit.AmazonSQS 8.2.3` with `CloudEventify 2.1.102` and `CloudEventify.MassTransit 2.1.102` and when it's deserializing the message, I'm getting the following exception:

`fail: MassTransit[0]
      R-FAULT amazonsqs://us-east-1/StandardTestMessage d51c938e-fa67-45c8-99fd-b637b8126b43 00:00:01.1332044
      System.TypeLoadException: Method 'IsSupportedMessageType' in type 'Context' from assembly 'CloudEventify.MassTransit, Version=2.1.102.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
         at CloudEventify.MassTransit.Deserializer.Deserialize(MessageBody body, Headers headers, Uri destinationAddress)
         at CloudEventify.MassTransit.Deserializer.MassTransit.IMessageDeserializer.Deserialize(ReceiveContext receiveContext)
         at MassTransit.Middleware.DeserializeFilter.Send(ReceiveContext context, IPipe 1 next) in /_/src/MassTransit/Middleware/DeserializeFilter.cs:line 36
         at MassTransit.Middleware.RescueFilter 2.MassTransit.IFilter<TContext>.Send(TContext context, IPipe 1 next) in /_/src/MassTransit/Middleware/RescueFilter.cs:line 43`

My setup is super simple:

```
public static async Task Main(string[] args)
 {
     await CreateHostBuilder(args).Build().RunAsync();
 }
 public static IHostBuilder CreateHostBuilder(string[] args) =>
     Host.CreateDefaultBuilder(args)
         .ConfigureServices((hostContext, services) =>
         {
             _ = services.AddMassTransit(x =>
               {
                   var assembly = Assembly.GetEntryAssembly();
                   x.AddConsumers(assembly);
                   x.UsingAmazonSqs((context, cfg) =>
                   {
                       const string awsRegion = "us-east-1";
                       cfg.Host(awsRegion, h =>
                       {
                       });
                       cfg.UseCloudEvents().WithJsonOptions(json => json.WriteIndented = true);
                       cfg.ConfigureEndpoints(context);
                   });
               });
             services.AddHostedService<MessagePublisher>();
         });
```

My message and consumer are: 

```
    public class StandardTestMessage
    {
        public string Text { get; set; }
    }

    public class StandardTestMessageConsumer : IConsumer<StandardTestMessage>
    {
        readonly ILogger<StandardTestMessageConsumer> _logger;
        public StandardTestMessageConsumer(ILogger<StandardTestMessageConsumer> logger)
        {
            _logger = logger;
        }

        public Task Consume(ConsumeContext<StandardTestMessage> context)
        {
            _logger.LogInformation("Received Message: {Text}", context.Message.Text);
            return Task.CompletedTask;
        }
    }
```

The message is published in my `MessagePublisher` worker like this:

```
var message = new StandardTestMessage { Text = $"The time is {DateTimeOffset.Now}"};
await _bus.Publish(message, stoppingToken);
```

The message is sent to the error queue with this envelope: 

```
{
  "specversion": "1.0",
  "id": "b4090000-de52-b40e-4dbc-08dc96bc70e1",
  "source": "amazonsqs://us-east-1/mypc_MassTransitWithSQS_bus_soroyyg6kk4y71k4bdqjpxdjr5?durable=false\u0026autodelete=true",
  "time": "2024-06-27T15:18:47.1599548Z",
  "type": "MassTransitWithSQS.StandardQueue.StandardTestMessage",
  "datacontenttype": "application/json",
  "data": {
    "Text": "The time is 6/27/2024 11:18:47 AM -04:00"
  }
}
```

When I EXCLUDE the line `cfg.UseCloudEvents().WithJsonOptions(json => json.WriteIndented = true);` everything works fine and includes the following envelope:

```
{
  "messageId": "24f40000-de52-b40e-2934-08dc96be1022",
  "requestId": null,
  "correlationId": null,
  "conversationId": "24f40000-de52-b40e-c47d-08dc96be1025",
  "initiatorId": null,
  "sourceAddress": "amazonsqs://us-east-1/mypc_MassTransitWithSQS_bus_ru4yyyg6kk4y7mnebdqjpxox8g?durable=false&autodelete=true",
  "destinationAddress": "amazonsqs://us-east-1/MassTransitWithSQS_StandardQueue-StandardTestMessage?type=topic",
  "responseAddress": null,
  "faultAddress": null,
  "messageType": [
    "urn:message:MassTransitWithSQS.StandardQueue:StandardTestMessage"
  ],
  "message": {
    "text": "The time is 6/27/2024 11:30:23 AM -04:00"
  },
  "expirationTime": null,
  "sentTime": "2024-06-27T15:30:23.8394676Z",
  "headers": {},
  "host": {
    "machineName": "mypc",
    "processName": "MassTransitWithSQS",
    "processId": 62500,
    "assembly": "MassTransitWithSQS",
    "assemblyVersion": "1.0.0.0",
    "frameworkVersion": "7.0.16",
    "massTransitVersion": "8.2.3.0",
    "operatingSystemVersion": "Microsoft Windows NT 10.0.22631.0"
  }
}
```

What am I missing in my setup to use CloudEventify? - thanks!!

**Comment by riezebosch** [comment]
Apparently MassTransit introduced a breaking change in one of the interfaces? Will look into that or you maybe you can help me out here 😄

**Comment by riezebosch** [comment]
Should be solved by now: https://www.nuget.org/packages/CloudEventify.MassTransit/2.2.110

**Comment by cjabbour** [comment]
That was a super quick turn-around @riezebosch thank you so much - it's working great!
