### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by imfaber** [riezebosch/MassTransit.CloudEvents#24]
Hello @riezebosch 

We are using this package and would like to continue doing so, but we are currently conducting an audit of all package licenses.

Unlicensed packages need to be addressed, so we were wondering if it would be possible for you to license this package. This would help us take any necessary actions if required.

Many thanks.

**Comment by riezebosch** [comment]
done https://github.com/riezebosch/CloudEventify/commit/042fa830885aefacd6ec44d0acbb12e66199b236
