### ISSUE TITLE
Headers are missing in the Published event

### ISSUE THREAD

**Issue by patelbinal** [riezebosch/MassTransit.CloudEvents#4]
Is there any way we could pass the Headers as well in the Cloud Events published? I could not see any property in which we can set it. When the Message Got serialized, I did not find the Headers we set while publishing an event by using the below code attached.

Message we can see in the RabbitMQ Management UI is as below:
`{
   "specversion":"1.0",
   "source":"rabbitmq://localhost:0/DESKTOPC8LSSLH_iisexpress_bus_be8oyyncpyyqbfw8bdpdgwt9yc?temporary=true",
   "id":"0a0f0000-4c68-00e0-ae43-08da335258f2",
   "type":"CreateOfferMessage",
   "time":"2022-05-11T13:29:59.8980675Z",
   "data":{
      "CreateRequestedDateTime":"2022-05-11T18:59:31.2023161+05:30",
      "OfferId":"00000000-0000-0000-0000-000000000000",
      "OfferDatabaseId":0,
      "OfferAmount":0,
      "CurrentStatus":"Submitted"
   }
}`

We are setting the Headers currently in the Headers property of SendContext object of whatever the event we publish.

**public async Task Send<T>(
            T record,
            string url,
            string token)
            where T : class
        {
            var sendEndpoint =
                await GetSendEndpoint(new Uri(url));

            await sendEndpoint.Send<T>(
                record,
                context =>
                {
                    context.Headers.Set(
                        MessageHeaders.Authorization,
                        token);

                    context.Headers.Set(
                        MessageHeaders.MessageType,
                        MessageType.Command.ToString());
                });
        }**

**Comment by patelbinal** [comment]
@riezebosch Can you please review the issue reported above?

**Comment by riezebosch** [comment]
I'm not sure what to do about it. If you look at the cloud events spec there is little room for such extensions since you are losing interoperability real quick. It's either data or standard. Not sure why MassTransit isn't picking it up since the only thing I replace is the serializer/deserializer.
